version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_sqs}"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
      - "4571:4571"
    environment:
      - DEBUG=1
      - AWS_DEFAULT_REGION=sa-east-1
    volumes:
      - "./init.sh:/etc/localstack/init/ready.d/init.sh"
